_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 83
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.16
            "5": 0.18.5
            "6": 4.46.1
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
